services:
  ethnode_requestor:
    build:
      context: ethnode_requestor
      dockerfile: Dockerfile
    environment:
      - MONITOR_DB_ENGINE=${MONITOR_DB_ENGINE}
      - YAGNA_API_URL=http://yagna_requestor_node:7465
      - YAGNA_MARKET_URL=http://yagna_requestor_node:7465/market-api/v1
      - YAGNA_ACTIVITY_URL=http://yagna_requestor_node:7465/activity-api/v1
      - YAGNA_PAYMENT_URL=http://yagna_requestor_node:7465/payment-api/v1
      - YAGNA_MONITOR_URL=http://yagna_requestor_node:3333
      - YAGNA_APPKEY=${YAGNA_APPKEY}
      - GATEWAY_BASE_URL=${GATEWAY_BASE_URL}
      - SUBNET=${SUBNET}
      - NUM_INSTANCES=${NUM_INSTANCES}
    command: run.sh
    restart: unless-stopped
    ports:
      - "${ETHNODE_PORT}:8545"    
  yagna_requestor_node:
    build:
      context: yagna_requestor_node
      dockerfile: Dockerfile
    image: yagna_requestor_node
    volumes:
      - "./yagna_dir:/root/.local/share/yagna"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MONITOR_DB_ENGINE=${MONITOR_DB_ENGINE}
      - GSB_URL=tcp://0.0.0.0:7464
      - YAGNA_API_URL=http://0.0.0.0:7465
      - YAGNA_APPKEY=${YAGNA_APPKEY}
      - YAGNA_AUTOCONF_ID_SECRET=${YAGNA_AUTOCONF_ID_SECRET}
      - ADDR=${ADDR}
      - YAGNA_AUTOCONF_APPKEY=${YAGNA_APPKEY}
    command: run.sh
    restart: unless-stopped
    ports:
      - "${YAGNA_MON_PORT}:3333"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS=500
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    restart: unless-stopped
      