services:
  postgres:
    image: postgres
    restart: on-failure
    env_file:
      - postgres.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - pgadmin.env
    volumes:
      - ./pgadmin:/var/lib/pgadmin
