services:
  ethnode_requestor:
    build:
      context: ethnode_requestor
      dockerfile: Dockerfile
    env_file:
      - private_ethnode_config.env
    environment:
      - YAGNA_API_URL=http://yagna_requestor_node:7465
      - YAGNA_MARKET_URL=http://yagna_requestor_node:7465/market-api/v1
      - YAGNA_ACTIVITY_URL=http://yagna_requestor_node:7465/activity-api/v1
      - YAGNA_PAYMENT_URL=http://yagna_requestor_node:7465/payment-api/v1
      - YAGNA_MONITOR_URL=http://yagna_requestor_node:3333
    command: run.sh
    ports:
      - "8545:8545"
    restart: unless-stopped
  yagna_requestor_node:
    build:
      context: yagna_requestor_node
      dockerfile: Dockerfile
    image: yagna_requestor_node
    env_file:
      - private_node_config.env
    volumes:
      - "./yagna_dir:/root/.local/share/yagna"
    environment:
      - GSB_URL=tcp://0.0.0.0:7464
      - YAGNA_API_URL=http://0.0.0.0:7465
    ports:
      - "3333:3333"      
    command: run.sh
    restart: unless-stopped
