services:
  ethnode_requestor:
    build:
      context: ethnode_requestor
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gateway
      - MONITOR_DB_ENGINE=postgres
      - YAGNA_API_URL=http://yagna_requestor_node:7465
      - YAGNA_MARKET_URL=http://yagna_requestor_node:7465/market-api/v1
      - YAGNA_ACTIVITY_URL=http://yagna_requestor_node:7465/activity-api/v1
      - YAGNA_PAYMENT_URL=http://yagna_requestor_node:7465/payment-api/v1
      - YAGNA_MONITOR_URL=http://yagna_requestor_node:3333
      - YAGNA_APPKEY=${YAGNA_APPKEY}
      - GATEWAY_BASE_URL=${GATEWAY_BASE_URL}
      - SUBNET=${SUBNET}
      - NUM_INSTANCES=${NUM_INSTANCES}
      - ALLOWED_ENDPOINT=${ALLOWED_ENDPOINT}
      - POLYGON_BACKUP_RPC=${POLYGON_BACKUP_RPC}
      - MUMBAI_BACKUP_RPC=${MUMBAI_BACKUP_RPC}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    command: ./run.sh
    restart: unless-stopped
    ports:
      - "${ETHNODE_PORT}:8545"
  yagna_requestor_node:
    build:
      context: yagna_requestor_node
      dockerfile: Dockerfile
    image: yagna_requestor_node
    volumes:
      - "${DATADIR}/yagna:/root/.local/share/yagna"
    environment:
      - GSB_URL=tcp://0.0.0.0:7464
      - YAGNA_API_URL=http://0.0.0.0:7465
      - YAGNA_APPKEY=${YAGNA_APPKEY}
      - YAGNA_AUTOCONF_ID_SECRET=${YAGNA_AUTOCONF_ID_SECRET}
      - YAGNA_AUTOCONF_APPKEY=${YAGNA_APPKEY}
    command: ./run.sh
    restart: unless-stopped
  frontend:
    build:
      context: golem-rpc-frontend
      dockerfile: Dockerfile    
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - "${DATADIR}/frontend:/app/etc"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gateway
    volumes:
      - ${DATADIR}/postgres:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS=500
      - SCRIPT_NAME=${PGADMIN_BASE_URL}
    volumes:
      - ${DATADIR}/pgadmin:/var/lib/pgadmin
    restart: unless-stopped
