services:
  yagna_requestor_node:
    build:
      context: yagna_requestor_node
      dockerfile: Dockerfile
    image: yagna_requestor_node
    env_file:
      - private_node_config.env
    volumes:
      - "./yagna_dir:/root/.local/share/yagna"
    ports:
      - "3333:3333"
      - "7465:7465"
    environment:
      - GSB_URL=tcp://0.0.0.0:7464
      - YAGNA_API_URL=http://0.0.0.0:7465      
    command: run.sh
    