services:
  postgres:
    image: postgres
    restart: on-failure
    env_file:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev_pass
      - POSTGRES_DB=dev
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@dev.com
      - PGADMIN_DEFAULT_PASSWORD=dev_pass
      - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS=500
    volumes:
      - ./pgadmin:/var/lib/pgadmin
