services:
  ethnode_requestor:
    build:
      context: ethnode_requestor
      dockerfile: Dockerfile
    env_file:
      - public_ethnode_config.env
      - private_ethnode_config.env
    command: run.sh
    ports:
      - "8545:8545"
  yagna_requestor_node:
    build:
      context: yagna_requestor_node
      dockerfile: Dockerfile
    image: yagna_requestor_node
    env_file:
      - public_node_config.env
      - private_node_config.env
    volumes:
      - "./yagna_dir:/root/.local/share/yagna"
    ports:
      - "3333:3333"      
    command: run.sh
      